steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/polleyg/gcp-batch-ingestion-bigquery.git']
- name: 'gcr.io/cloud-builders/gradle'
  args: ['build', 'run']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'goWithTheDataFlow', '--stage-bucket', 'gs://batch-pipeline', '--trigger-bucket', 'gs://batch-pipeline']
  dir: 'cloud-function'
artifacts:
  objects:
    location: 'gs://batch-pipeline/artifacts'
    paths: ['build/distributions/*.*']