steps:
  #Fetch the source code
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/polleyg/gcp-batch-ingestion-bigquery.git']

- name: gcr.io/cloud-builders/docker
  args: ['pull', 'hashicorp/terraform']

- name: gcr.io/cloud-builders/docker
  args: ['run', 'hashicorp/terraform','init']
  dir: 'terraform'

  #Build and run the Dataflow pipeline (staged template)
- name: gcr.io/cloud-builders/gradle
  args: ['build', 'run']

  #Deploy the Cloud Function that listens to the bucket
- name: gcr.io/cloud-builders/gcloud
  args: ['functions', 'deploy', 'goWithTheDataFlow', '--stage-bucket=gs://batch-pipeline', '--trigger-bucket=gs://batch-pipeline']
  dir: 'cloud-function'

  #Copy tarball to GCS to use later
artifacts:
  objects:
    location: 'gs://batch-pipeline/artifacts'
    paths: ['build/distributions/*.*']